---
title: "Online Books on Data Science and Statistics"
output: github_document
---

1.  [R for Data Science - Garrett Grolemund, Hadley Wickham](https://r4ds.had.co.nz/)

2.  [Tales and stats in R - Lise Vaudor](http://perso.ens-lyon.fr/lise.vaudor/grimoireStat/_book/)

3.  [Learning statistics with R: A tutorial for psychology students and other beginners - Danielle Navarro](https://learningstatisticswithr.com/book/)

4.  [R Markdown: The Definitive Guide - Yihui Xie, J. J. Allaire, Garrett Grolemund](https://bookdown.org/yihui/rmarkdown/)

5.  [Statistical Modeling: Computational Technique - Daniel Kaplan and Frank Shaw](http://mosaic-web.org/go/SM2-technique/)

6.  [The Plain Person's Guide to Plain Text Social Science - Kieran Healy](http://plain-text.co/index.html#introduction)

7.  [Data Visualization - A Practical Introduction - Kieran Healy](https://socviz.co/)

8.  [Fundamentals of Data Visualization - Claus O. Wilke](https://serialmentor.com/dataviz/)

9.  [Interactive webbased data visualization with R, plotly, and shiny - Carson Sievert](https://plotly-r.com/)

10. [Modern R with the tidyverse - Bruno Rodrigues](https://b-rodrigues.github.io/modern_R/)

11. [Statistical Inference via Data Science: A moderndive into R and the tidyverse - Chester Ismay and Albert Y. Kim](https://moderndive.com/)

12. [Text Mining with R - A Tidy Approach - Julia Silge and David Robinson](https://www.tidytextmining.com/)

13. [Univ of Cincinnatti Business Analytics R Programming Guide - Bradley Boehmke](https://uc-r.github.io/)

14. [Interpretable Machine Learning - A Guide for Making Black Box Models Explainable - Christoph Molnar](https://christophm.github.io/interpretable-ml-book/)

15. [Introduction to Data Science : Data Analysis and Prediction Algorithms with R - Rafael A. Irizarry](https://rafalab.github.io/dsbook/)

16. [The tidyverse style guide - Hadley Wickham](https://style.tidyverse.org/)

17. [Practical Regression and ANOVA with R - Julian Farraway](https://cloud.r-project.org/doc/contrib/Faraway-PRA.pdf)

18. [R Cookbook - Winston Chang](http://www.cookbook-r.com/Graphs/)

19. [Statistical Thinking for the 21st Century - Russell A. Poldrack](http://statsthinking21.org/index.html)

## Blogs

1.  [Susan Baert on `dplyr`](https://suzanbaert.netlify.com/2018/01/dplyr-tutorial-1/)

2.  [Gina Reynolds - The `Tidyverse` Flip Book](https://evamaerey.github.io/tidyverse_in_action/tidyverse_in_action.html#1)

3.  [Gina Reynolds - The `ggplot` Flip Book](https://evamaerey.github.io/ggplot_flipbook/ggplot_flipbook_xaringan.html#1)

4.  [Garrick Aden-Buie - A Gentle Guide to the Grammar of Graphics with ggplot2](https://gadenbuie.github.io/gentle-ggplot2)

5.  [Teaching Undergrad Stats without p, F, or t. - Jeff Rouder](https://jeffrouder.blogspot.com/2019/03/teaching-undergrad-stats-without-p-f-or.html)
